# version: "3.9"
# services:
#   api:
#     build: ./backend
#     env_file: .env
#     volumes:
#       - ./backend:/app
#       - ./data:/data
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#   db:
#     image: postgres:16
#     environment:
#       POSTGRES_DB: nisaa
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: pass
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
