name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Service to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy on EC2
        env:
          OPENAI_API_KEY: ${{ secrets.DEV_OPENAI_API_KEY }}
        run: |
          echo "🔐 Connecting to EC2 and deploying service..."

          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<'EOF'
            set -e

            DEPLOY_DIR=~/deployments/web_scraping_chatbot
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            # Clone if missing, otherwise pull latest
            if [ ! -d ".git" ]; then
              echo "🌀 Cloning repository..."
              git clone https://github.com/arpitkumar20/Web_Scraping_ChatBot.git .
            else
              echo "🔄 Pulling latest changes..."
              git fetch origin
              git reset --hard origin/main
            fi

            
            sed -i "s|ENV_OPENAI_API_KEY|${{ vars.DEV_OPENAI_API_KEY }}|g" backend/.env
            cat backend/.env
            

            echo "🚀 Redeploying with Docker Compose..."
            sudo docker-compose down || true
            sudo docker-compose up -d --build

            echo "✅ Deployment completed successfully!"
          EOF
