name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Service to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy on EC2
        env:
          OPENAI_API_KEY: ${{ secrets.DEV_OPENAI_API_KEY }}
        run: |
          echo "🔐 Connecting to EC2 and deploying service..."

          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<EOF
            set -e
            cd /home/ubuntu/deployments/web_scraping_chatbot

            echo "📦 Pulling latest code..."
            git pull origin main

            echo "🧩 Updating .env file..."
            # Ensure .env exists
            touch backend/.env

            # Clean and update OPENAI_API_KEY
            sed -i "/^OPENAI_API_KEY=/d" backend/.env || true
            echo "OPENAI_API_KEY=${DEV_OPENAI_API_KEY}" >> backend/.env

            echo "🐳 Checking Docker setup..."
            if ! command -v docker-compose &> /dev/null; then
              echo "⚙️ Installing docker-compose..."
              sudo apt-get update -y
              sudo apt-get install -y docker-compose
            fi

            echo "🚀 Deploying Docker Compose..."
            sudo docker-compose down
            sudo docker-compose up -d --build

            echo "✅ Deployment completed successfully!"
EOF
