name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Service to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy on EC2
        env:
          OPENAI_API_KEY: ${{ secrets.DEV_OPENAI_API_KEY }}
        run: |
          echo "🔐 Connecting to EC2 and deploying service..."

          # ✅ FIX: Removed single quotes around EOF so variable expands correctly
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<EOF
            set -e
            DEPLOY_DIR=~/deployments/web_scraping_chatbot
            mkdir -p \$DEPLOY_DIR
            cd \$DEPLOY_DIR

            echo "📦 Pulling latest code..."
            git pull origin main

            echo "🧩 Updating .env file..."
            # Update the .env file inside backend folder with the GitHub secret
            sed -i "/^OPENAI_API_KEY=/d" backend/.env || true
            echo "OPENAI_API_KEY=${DEV_OPENAI_API_KEY}" >> backend/.env

            echo "🚀 Deploying Docker Compose..."
            sudo docker-compose down
            sudo docker-compose up -d --build

            echo "✅ Deployment completed successfully!"
           EOF
